### ISSUE TITLE
这个网站的伪静态咋配置呢，我一刷新就404

### ISSUE THREAD

**Issue by 204065248** [synctv-org/synctv-web#71]
rt
这是我的伪静态配置
```
location /web/ {
    rewrite ^/web/(.*)$ /$1 last;
}
```

**Comment by zijiren233** [comment]
不是伪静态，这个web本来就是静态的。
你需要使用的是nginx的tryfile功能，
或者使用synctv启动参数让synctv直接读取目录里的web文件

**Comment by 204065248** [comment]
tryfile咋配置呢

**Comment by zijiren233** [comment]
你是自己编译了前端吗？
具体咋配置tryfile可以去搜一下vue的tryfile配置。
最简单的方法还是使用synctv的启动参数直接读取目录里面的web文件

**Comment by 204065248** [comment]
synctv我是用docker镜像的，我用的编译好的。重装电脑没弄node环境

**Comment by zijiren233** [comment]
如果你没有想要定制化web，那应该不需要任何特殊的nginx配置就能用呀，web是默认打包到synctv里面的
